name: xournalpp
description: A port of the main features of Xournal++ to various Flutter platforms like Android, iOS and the Web.

publish_to: none

version: 4.1.7+19

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^11.0.2
  flutter_math_fork: ^0.7.4
  intl: ^0.20.0
  archive: ^4.0.9
  xml: ^6.5.0
  url_launcher: ^6.3.2
#  catcher: ^0.4.0
  receive_sharing_intent: ^1.9.0
  flutter_dropzone: ^4.2.1
  shared_preferences: ^2.5.5
  share_plus: ^11.1.0
  vector_math: ^2.2.0
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^9.0.1
  path_provider: ^2.1.5
  pdf: ^3.12.0
#  zefyr: ^0.12.0
#  notus: ^0.1.5

  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^11.0.0
  pdfrx: ^2.4.4
  pdfium_flutter: ^0.2.2
  image: ^4.8.0
dev_dependencies:
  flutter_test:
    sdk:
      flutter
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  file: ^7.0.1

flutter_icons:
   android: true
   ios: true
   image_path: "assets/xournalpp.png"
   image_path_ios: "assets/xournalpp.png"
   image_path_android: "assets/xournalpp.png"
   adaptive_icon_background: "#ddecf4"
   adaptive_icon_foreground: "assets/xournalpp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/Open Sans/OpenSans-Regular.ttf
        - asset: fonts/Open Sans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/Open Sans/OpenSans-ExtraBold.ttf
          weight: 800
    - family: Glacial Indifference
      fonts:
        - asset: fonts/Glacial Indifference/GlacialIndifference-Regular.otf

flutter_intl:
  enabled: true
